### ISSUE TITLE
API Functionality on prosperityhomeowner.com

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/prosperityhomeowner.com#1]
@codextiny I am building the page now but will need same search bar functionality and both "get started" button functionality on home page just like you did for [everythinghome.ai](url)

**Comment by shannonbaldwin** [comment]
prosperityhomeowner.com/agents[](url)

How do I remove the round circle on the cursor for this site? ![image](https://github.com/shannonbaldwin/prosperityhomeowner.com/assets/167017886/5723196a-bfb3-47c4-a69c-3b27001ed236)

**Comment by codextiny** [comment]
@shannonbaldwin 

We are working on it.

**Comment by codextiny** [comment]
@shannonbaldwin 

We have added the popup please have a look.

**Comment by shannonbaldwin** [comment]
@codextiny Please update the "Claim my home" CTA buttons on bottom of home page and the two on How it Works page to direct to the same pop up form as "Get Started"<img width="1095" alt="image" 
src="https://github.com/shannonbaldwin/prosperityhomeowner.com/assets/167017886/934894f0-aee1-4acf-add4-ce4b6d89e498"><img width="1402" alt="image" src="https://github.com/shannonbaldwin/prosperityhomeowner.com/assets/167017886/439ed245-2196-451e-9832-08d966350e9a"><img width="1173" alt="image" src="https://github.com/shannonbaldwin/prosperityhomeowner.com/assets/167017886/e2ec8bfb-e440-4c76-8aaa-8d5398d4f8cf">

**Comment by codextiny** [comment]
@shannonbaldwin 

We have updated the buttons please check.
