### ISSUE TITLE
Black screen when clicking through different pages

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/prosperityhomeowner.com#3]
Please remove the black screen that pops up on each website. See video below. 

https://github.com/shannonbaldwin/prosperityhomeowner.com/assets/167017886/f09f3639-889a-4920-83c2-0844f9aca4ba

**Comment by codextiny** [comment]
@shannonbaldwin 

We have seen the video, its basically the page transition which is applied by "Outgrid Layout", please ee screenshot to remove the transition.

![image](https://github.com/shannonbaldwin/prosperityhomeowner.com/assets/113863175/a4321195-ab81-45ba-81ef-1fb7dbf056ba)


Thanks,
Codextiny
