### ISSUE TITLE
Underline color on training page

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/prosperityhomeowner.com#4]
How can I update the underline color to the secondary global color here? [https://prosperityhomeowner.com/agents/support-and-training/](url)
![image](https://github.com/shannonbaldwin/prosperityhomeowner.com/assets/167017886/ccbbd267-f8c0-400b-820c-ff5c40a97e7f)

**Comment by codextiny** [comment]
@shannonbaldwin 

please see screenshot to update the border color.

![image](https://github.com/shannonbaldwin/prosperityhomeowner.com/assets/113863175/e94dfb02-739a-4b51-932f-7a2a73b8a62b)

Thanks,
Codextiny
