### ISSUE TITLE
Copying Footer 

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/prosperityhomeowner.com#6]
@codextiny How do I copy the footer from[ https://prosperityhomeowner.com/team/] to[(https://prosperityhomeowner.com/)]??
![image](https://github.com/shannonbaldwin/prosperityhomeowner.com/assets/167017886/c339c078-f752-4952-aad1-5ed760cd1862)

**Comment by codextiny** [comment]
@shannonbaldwin 

both are on different domains ??

**Comment by codextiny** [comment]
@shannonbaldwin 

We have added footer from https://prosperityhomeowner.com/team/ to https://prosperityhomeowner.com, you just need to copy the section and select the option on other domain "paste from other site" the section will be copied to other domain. one thing need to mention here both elementor versions will be same and should be paid.

![image](https://github.com/shannonbaldwin/prosperityhomeowner.com/assets/113863175/2a817415-99d5-44ee-87ab-2b8aaa7bd4ab)

please check.

**Comment by shannonbaldwin** [comment]
@codextiny There should be two licenses for Elementor and one for each. Thank you!

**Comment by shannonbaldwin** [comment]
@codextiny I think something happened to the CTA banner above the footer when you copied it over. The image is gone.![image](https://github.com/shannonbaldwin/prosperityhomeowner.com/assets/167017886/e614a25d-514f-4582-8500-497d4303d6bc)
[
](https://prosperityhomeowner.com/team/how-it-works/)

**Comment by codextiny** [comment]
@shannonbaldwin 
can you please provide the link, this section not in homepage ??

**Comment by shannonbaldwin** [comment]
@codextiny It is back! Please disregard. It was on prosperityhomeowner.com/team/how-it-works/
