### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/prosperityhomeowner.com#7]
@shannonbaldwin 

We have added footer from https://prosperityhomeowner.com/team/ to https://prosperityhomeowner.com, you just need to copy the section and select the option on other domain "paste from other site" the section will be copied to other domain. one thing need to mention here both elementor versions will be same and should be paid.

![image](https://github.com/shannonbaldwin/prosperityhomeowner.com/assets/113863175/2a817415-99d5-44ee-87ab-2b8aaa7bd4ab)

please check.

_Originally posted by @codextiny in https://github.com/shannonbaldwin/prosperityhomeowner.com/issues/6#issuecomment-2166069842_

**Comment by shannonbaldwin** [comment]
@codextiny Please correct the bottom button on footer for mobile. 
![image](https://github.com/shannonbaldwin/prosperityhomeowner.com/assets/167017886/ce4c145d-8e38-41d7-bbd2-4ae9f2cfb673)

**Comment by codextiny** [comment]
@shannonbaldwin 

Fixed, please check.
